#!/bin/bash

SCRIPT_NAME='octodns-alias'

matches_debug() {
  if [ -z "$DEBUG" ]; then
    return 1
  fi
  if [[ $SCRIPT_NAME == "$DEBUG" ]]; then
    return 0
  fi
  return 1
}

debug() {
  local cyan='\033[0;36m'
  local no_color='\033[0;0m'
  local message="$@"
  matches_debug || return 0
  (>&2 echo -e "[${cyan}${SCRIPT_NAME}${no_color}]: $message")
}

err_echo() {
  local message
  message="$1"
  echo "$message" 1>&2
}

fatal() {
  local message
  message="$1"

  err_echo "$message"
  exit 1
}

script_directory(){
  local source="${BASH_SOURCE[0]}"
  local dir=""

  while [ -h "$source" ]; do # resolve $source until the file is no longer a symlink
    dir="$( cd -P "$( dirname "$source" )" && pwd )"
    source="$(readlink "$source")"
    [[ $source != /* ]] && source="$dir/$source" # if $source was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  done

  dir="$( cd -P "$( dirname "$source" )" && pwd )"

  echo "$dir"
}

assert_required_information() {
  local domain="$1"
  local zone_name="$2"

  if [ -n "$domain" ] && [ -n "$zone_name" ]; then
    return 0
  fi

  if [ -z "$domain" ]; then
    echo "dns.json file was missing a '.domain' property"
  fi

  if [ -z "$zone_name" ]; then
    echo "dns.json file was missing a '.zoneName' property"
  fi

  exit 1
}

assert_required_params() {
  local dns_json_path="$1"

  if [ -n "$dns_json_path" ] && [ -r "$dns_json_path" ]; then
    return 0
  fi

  usage

  if [ -z "$dns_json_path" ]; then
    echo "Missing </path/to/dns.json>"
  elif [ ! -r "$dns_json_path" ]; then
    echo "File at '$dns_json_path' is either not a file, or is unreadable"
  fi

  exit 1
}

usage(){
  echo "USAGE:"
  echo "  ${SCRIPT_NAME} [OPTIONS] </path/to/dns.json>"
  echo ''
  echo 'DESCRIPTION:'
  echo '  Will convert the aliasRecords portion in </path/to/dns.json>'
  echo '  to Route53 change format and POST it up to AWS'
  echo ''
  echo 'OPTIONS:'
  echo '  -h, --help       print this help text'
  echo '  -n, --dry-run    do a dry run'
  echo '  -v, --version    print the version'
  echo ''
  echo 'ENVIRONMENT:'
  echo '  DEBUG            print debug output'
  echo ''
}

version(){
  local directory
  directory="$(script_directory)"

  if [ -f "$directory/VERSION" ]; then
    cat "$directory/VERSION"
  else
    echo "unknown-version"
  fi
}

generate_change(){
  local domain dns_json_path elb elb_name name template
  dns_json_path="$1"
  domain="$2"
  name="$3"

  read -r -d '' template <<'EOF'
  {
    "Action": "UPSERT",
    "ResourceRecordSet": {
      "Name": null,
      "Type": "A",
      "AliasTarget": {
        "HostedZoneId": null,
        "DNSName": null,
        "EvaluateTargetHealth": false
      }
    }
  }
EOF

  elb_name="$(jq --raw-output ".aliasRecords[\"$name\"].elb" "$dns_json_path")" || return $?
  hostname="$name.$domain"
  elb="$(get_elb "$elb_name")" || return $?
  hosted_zone_id="$(echo "$elb" | jq --raw-output '.CanonicalHostedZoneNameID')" || return $?
  dns_name="$(echo "$elb" | jq --raw-output '.CanonicalHostedZoneName')" || return $?

  template="$(echo "$template" | jq --arg hostname "$hostname" '.ResourceRecordSet.Name = $hostname')"
  template="$(echo "$template" | jq --arg hostedZoneId "$hosted_zone_id" '.ResourceRecordSet.AliasTarget.HostedZoneId = $hostedZoneId')"
  template="$(echo "$template" | jq --arg dnsName "$dns_name" '.ResourceRecordSet.AliasTarget.DNSName = $dnsName')"

  echo "$template"
}

generate_change_batch() {
  local change dns_json_path domain names output
  dns_json_path="$1"
  domain="$2"

  names=( $(get_alias_names "$dns_json_path") ) || return 1
  output='{"Comment": "Stack Updating DNS", "Changes": []}'

  for name in "${names[@]}"; do
    change="$(generate_change "$dns_json_path" "$domain" "$name")" || return 1
    output="$(echo "$output" | jq --argjson change "$change" '.Changes += [$change]')"
  done

  echo "$output"
}

get_alias_names(){
  local dns_json_path num_keys
  dns_json_path="$1"

  num_keys="$(jq --raw-output '.aliasRecords | length' "$dns_json_path")"
  if [ "$num_keys" == "0" ]; then
    return
  fi

  jq --raw-output '.aliasRecords | keys | .[]' "$dns_json_path"
}

get_domain() {
  local dns_json_path="$1"

  jq --raw-output '.domain' "$dns_json_path"
}

get_elb(){
  set -o pipefail

  local elb_name output
  elb_name="$1"

  output="$(aws elb describe-load-balancers --load-balancer-names "$elb_name")" || return $?
  output="$(echo -n "$output" | jq --raw-output '.LoadBalancerDescriptions[0]')" || return $?

  if [ -z "$output" ] || [ "$output" == "null" ]; then
    err_echo "Could not find load balancer '$elb_name'"
    return 1
  fi

  echo "$output"
}

get_route53_hosted_zone(){
  local zone_name="$1"

  aws route53 list-hosted-zones \
  | jq --raw-output ".HostedZones | map(select(.Name == \"$zone_name\"))[0].Id"
}

get_zone_name() {
  local dns_json_path="$1"

  jq --raw-output '.zoneName' "$dns_json_path"
}


main() {
  # Define args up here
  local domain dns_json_path dry_run

  while [ "$1" != "" ]; do
    local param="$1"
    # local value="$2"
    case "$param" in
      -h | --help)
        usage
        exit 0
        ;;
      -v | --version)
        version
        exit 0
        ;;
      # Arg with value
      # -x | --example)
      #   example="$value"
      #   shift
      #   ;;
      # Arg without value
      -n | --dry-run)
        dry_run='true'
        ;;
      *)
        if [ "${param::1}" == '-' ]; then
          echo "ERROR: unknown parameter \"$param\""
          usage
          exit 1
        fi
        # Set main arguments
        if [ -z "$dns_json_path" ]; then
          dns_json_path="$param"
        # elif [ -z "$main_arg_2"]; then
        #   main_arg_2="$param"
        fi
        ;;
    esac
    shift
  done

  assert_required_params "$dns_json_path"

  domain="$(get_domain "$dns_json_path")" || exit 1
  zone_name="$(get_zone_name "$dns_json_path")" || exit 1
  assert_required_information "$domain" "$zone_name"

  route53_hosted_zone=$(get_route53_hosted_zone "$zone_name")
  if [ -z "$route53_hosted_zone" ] || [ "$route53_hosted_zone" == "null" ]; then
    echo "Could not find route53 hosted zone for: $zone_name" 2>&1
    exit 1
  fi

  change_batch="$(generate_change_batch "$dns_json_path" "$domain")"

  if [ "$dry_run" == "true" ]; then
    echo "$change_batch"
    exit 0
  fi

  tmpfile="$(mktemp)"
  echo "$change_batch" > "$tmpfile"

  aws route53 \
    change-resource-record-sets \
    --hosted-zone-id "$route53_hosted_zone" \
    --change-batch "file://$tmpfile" || fatal 'Unable to create route'
}

main "$@"
